# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'ui_can.ui'
##
## Created by: Qt User Interface Compiler version 6.6.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractScrollArea, QApplication, QCheckBox, QComboBox,
    QFrame, QGroupBox, QHBoxLayout, QHeaderView,
    QLabel, QLayout, QLineEdit, QPushButton,
    QScrollArea, QSizePolicy, QSpacerItem, QTabWidget,
    QTableWidget, QTableWidgetItem, QVBoxLayout, QWidget)

class Ui_CAN(object):
    def setupUi(self, CAN):
        if not CAN.objectName():
            CAN.setObjectName(u"CAN")
        CAN.resize(1273, 900)
        font = QFont()
        font.setFamilies([u"D2Coding"])
        font.setPointSize(12)
        CAN.setFont(font)
        self.horizontalLayout_3 = QHBoxLayout(CAN)
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.verticalLayout = QVBoxLayout()
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setSizeConstraint(QLayout.SizeConstraint.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.combo_open_mode = QComboBox(CAN)
        self.combo_open_mode.addItem("")
        self.combo_open_mode.addItem("")
        self.combo_open_mode.addItem("")
        self.combo_open_mode.setObjectName(u"combo_open_mode")
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_open_mode.sizePolicy().hasHeightForWidth())
        self.combo_open_mode.setSizePolicy(sizePolicy)

        self.horizontalLayout.addWidget(self.combo_open_mode)

        self.line = QFrame(CAN)
        self.line.setObjectName(u"line")
        self.line.setFrameShape(QFrame.VLine)
        self.line.setFrameShadow(QFrame.Sunken)

        self.horizontalLayout.addWidget(self.line)

        self.label = QLabel(CAN)
        self.label.setObjectName(u"label")

        self.horizontalLayout.addWidget(self.label)

        self.combo_open_rate_normal = QComboBox(CAN)
        self.combo_open_rate_normal.setObjectName(u"combo_open_rate_normal")

        self.horizontalLayout.addWidget(self.combo_open_rate_normal)

        self.line_5 = QFrame(CAN)
        self.line_5.setObjectName(u"line_5")
        self.line_5.setFrameShape(QFrame.VLine)
        self.line_5.setFrameShadow(QFrame.Sunken)

        self.horizontalLayout.addWidget(self.line_5)

        self.btn_open = QPushButton(CAN)
        self.btn_open.setObjectName(u"btn_open")

        self.horizontalLayout.addWidget(self.btn_open)

        self.btn_close = QPushButton(CAN)
        self.btn_close.setObjectName(u"btn_close")

        self.horizontalLayout.addWidget(self.btn_close)

        self.label_rx_cnt = QLabel(CAN)
        self.label_rx_cnt.setObjectName(u"label_rx_cnt")
        self.label_rx_cnt.setMinimumSize(QSize(150, 0))

        self.horizontalLayout.addWidget(self.label_rx_cnt)

        self.label_rx_size = QLabel(CAN)
        self.label_rx_size.setObjectName(u"label_rx_size")

        self.horizontalLayout.addWidget(self.label_rx_size)

        self.horizontalSpacer = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout.addItem(self.horizontalSpacer)


        self.verticalLayout.addLayout(self.horizontalLayout)

        self.horizontalLayout_2 = QHBoxLayout()
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalLayout_2.setContentsMargins(0, -1, 0, 0)
        self.verticalLayout_2 = QVBoxLayout()
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setSizeConstraint(QLayout.SizeConstraint.SetDefaultConstraint)
        self.verticalLayout_2.setContentsMargins(0, -1, -1, -1)
        self.label_1111 = QLabel(CAN)
        self.label_1111.setObjectName(u"label_1111")

        self.verticalLayout_2.addWidget(self.label_1111)

        self.table_bldc = QTableWidget(CAN)
        self.table_bldc.setObjectName(u"table_bldc")
        self.table_bldc.setMinimumSize(QSize(550, 0))
        self.table_bldc.setMaximumSize(QSize(600, 16777215))
        self.table_bldc.horizontalHeader().setStretchLastSection(True)

        self.verticalLayout_2.addWidget(self.table_bldc)


        self.horizontalLayout_2.addLayout(self.verticalLayout_2)

        self.frame = QFrame(CAN)
        self.frame.setObjectName(u"frame")
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy1)
        self.frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QFrame.Shadow.Raised)
        self.verticalLayout_4 = QVBoxLayout(self.frame)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.verticalLayout_4.setContentsMargins(-1, -1, -1, 9)
        self.scrollArea = QScrollArea(self.frame)
        self.scrollArea.setObjectName(u"scrollArea")
        self.scrollArea.setSizeAdjustPolicy(QAbstractScrollArea.SizeAdjustPolicy.AdjustIgnored)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignTop)
        self.scrollAreaWidgetContents_2 = QWidget()
        self.scrollAreaWidgetContents_2.setObjectName(u"scrollAreaWidgetContents_2")
        self.scrollAreaWidgetContents_2.setGeometry(QRect(0, 0, 818, 818))
        self.horizontalLayout_4 = QHBoxLayout(self.scrollAreaWidgetContents_2)
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.frame_2 = QFrame(self.scrollAreaWidgetContents_2)
        self.frame_2.setObjectName(u"frame_2")
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Preferred)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy2)
        self.frame_2.setMinimumSize(QSize(800, 800))
        self.frame_2.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.frame_2.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Shadow.Raised)
        self.btn_send_1 = QPushButton(self.frame_2)
        self.btn_send_1.setObjectName(u"btn_send_1")
        self.btn_send_1.setGeometry(QRect(0, 20, 81, 24))
        self.lineEdit_send_1 = QLineEdit(self.frame_2)
        self.lineEdit_send_1.setObjectName(u"lineEdit_send_1")
        self.lineEdit_send_1.setGeometry(QRect(90, 20, 91, 22))
        self.comboBox_send_1 = QComboBox(self.frame_2)
        self.comboBox_send_1.setObjectName(u"comboBox_send_1")
        self.comboBox_send_1.setGeometry(QRect(190, 20, 301, 22))
        self.lineEdit_send_2 = QLineEdit(self.frame_2)
        self.lineEdit_send_2.setObjectName(u"lineEdit_send_2")
        self.lineEdit_send_2.setGeometry(QRect(90, 50, 91, 22))
        self.comboBox_send_2 = QComboBox(self.frame_2)
        self.comboBox_send_2.setObjectName(u"comboBox_send_2")
        self.comboBox_send_2.setGeometry(QRect(190, 50, 301, 22))
        self.btn_send_2 = QPushButton(self.frame_2)
        self.btn_send_2.setObjectName(u"btn_send_2")
        self.btn_send_2.setGeometry(QRect(0, 50, 81, 24))
        self.lineEdit_send_3 = QLineEdit(self.frame_2)
        self.lineEdit_send_3.setObjectName(u"lineEdit_send_3")
        self.lineEdit_send_3.setGeometry(QRect(90, 100, 91, 22))
        self.comboBox_send_3 = QComboBox(self.frame_2)
        self.comboBox_send_3.setObjectName(u"comboBox_send_3")
        self.comboBox_send_3.setGeometry(QRect(190, 100, 301, 22))
        self.btn_send_3 = QPushButton(self.frame_2)
        self.btn_send_3.setObjectName(u"btn_send_3")
        self.btn_send_3.setGeometry(QRect(0, 100, 81, 24))
        self.lineEdit_send_4 = QLineEdit(self.frame_2)
        self.lineEdit_send_4.setObjectName(u"lineEdit_send_4")
        self.lineEdit_send_4.setGeometry(QRect(90, 130, 91, 22))
        self.btn_send_4 = QPushButton(self.frame_2)
        self.btn_send_4.setObjectName(u"btn_send_4")
        self.btn_send_4.setGeometry(QRect(0, 130, 81, 24))
        self.comboBox_send_4 = QComboBox(self.frame_2)
        self.comboBox_send_4.setObjectName(u"comboBox_send_4")
        self.comboBox_send_4.setGeometry(QRect(190, 130, 301, 22))
        self.label_1 = QLabel(self.frame_2)
        self.label_1.setObjectName(u"label_1")
        self.label_1.setGeometry(QRect(500, 20, 251, 16))
        self.label_2 = QLabel(self.frame_2)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(500, 50, 271, 16))
        self.label_3 = QLabel(self.frame_2)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(500, 100, 271, 16))
        self.label_4 = QLabel(self.frame_2)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(500, 130, 291, 16))
        self.tabWidget = QTabWidget(self.frame_2)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(0, 180, 711, 611))
        self.tab_spine = QWidget()
        self.tab_spine.setObjectName(u"tab_spine")
        self.groupBox = QGroupBox(self.tab_spine)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(10, 10, 561, 131))
        self.checkBox_scan = QCheckBox(self.groupBox)
        self.checkBox_scan.setObjectName(u"checkBox_scan")
        self.checkBox_scan.setGeometry(QRect(380, 60, 76, 20))
        self.btn_spine_play = QPushButton(self.groupBox)
        self.btn_spine_play.setObjectName(u"btn_spine_play")
        self.btn_spine_play.setGeometry(QRect(10, 30, 75, 24))
        self.comboBox_masg_list = QComboBox(self.groupBox)
        self.comboBox_masg_list.setObjectName(u"comboBox_masg_list")
        self.comboBox_masg_list.setGeometry(QRect(240, 30, 107, 24))
        self.comboBox_masg_list.setMaximumSize(QSize(16777215, 16777215))
        self.comboBox_masg_list.setSizeAdjustPolicy(QComboBox.SizeAdjustPolicy.AdjustToContents)
        self.comboBox_masg_list.setMinimumContentsLength(10)
        self.btn_spine_stop = QPushButton(self.groupBox)
        self.btn_spine_stop.setObjectName(u"btn_spine_stop")
        self.btn_spine_stop.setGeometry(QRect(10, 90, 75, 24))
        self.btn_spine_pause = QPushButton(self.groupBox)
        self.btn_spine_pause.setObjectName(u"btn_spine_pause")
        self.btn_spine_pause.setGeometry(QRect(10, 60, 75, 24))
        self.label_5 = QLabel(self.groupBox)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(190, 30, 50, 20))
        self.comboBox_spine_strength = QComboBox(self.groupBox)
        self.comboBox_spine_strength.setObjectName(u"comboBox_spine_strength")
        self.comboBox_spine_strength.setGeometry(QRect(240, 60, 111, 22))
        self.label_6 = QLabel(self.groupBox)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(190, 60, 50, 20))
        self.pushButton = QPushButton(self.groupBox)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(90, 30, 75, 24))
        self.comboBox_spine_speed = QComboBox(self.groupBox)
        self.comboBox_spine_speed.setObjectName(u"comboBox_spine_speed")
        self.comboBox_spine_speed.setGeometry(QRect(240, 90, 111, 22))
        self.label_7 = QLabel(self.groupBox)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(190, 90, 50, 20))
        self.groupBox_3 = QGroupBox(self.tab_spine)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(10, 160, 561, 131))
        self.lineEdit_ptc_set = QLineEdit(self.groupBox_3)
        self.lineEdit_ptc_set.setObjectName(u"lineEdit_ptc_set")
        self.lineEdit_ptc_set.setGeometry(QRect(100, 20, 41, 22))
        self.btn_ptc_set = QPushButton(self.groupBox_3)
        self.btn_ptc_set.setObjectName(u"btn_ptc_set")
        self.btn_ptc_set.setGeometry(QRect(10, 20, 75, 24))
        self.label_8 = QLabel(self.groupBox_3)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(110, 50, 21, 16))
        self.label_9 = QLabel(self.groupBox_3)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(160, 50, 20, 16))
        self.label_10 = QLabel(self.groupBox_3)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(210, 50, 20, 16))
        self.label_11 = QLabel(self.groupBox_3)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(260, 50, 20, 16))
        self.lineEdit_ptc_get_1 = QLineEdit(self.groupBox_3)
        self.lineEdit_ptc_get_1.setObjectName(u"lineEdit_ptc_get_1")
        self.lineEdit_ptc_get_1.setGeometry(QRect(100, 70, 41, 22))
        self.label_12 = QLabel(self.groupBox_3)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(30, 70, 50, 16))
        self.lineEdit_ptc_get_2 = QLineEdit(self.groupBox_3)
        self.lineEdit_ptc_get_2.setObjectName(u"lineEdit_ptc_get_2")
        self.lineEdit_ptc_get_2.setGeometry(QRect(150, 70, 41, 22))
        self.lineEdit_ptc_get_3 = QLineEdit(self.groupBox_3)
        self.lineEdit_ptc_get_3.setObjectName(u"lineEdit_ptc_get_3")
        self.lineEdit_ptc_get_3.setGeometry(QRect(200, 70, 41, 22))
        self.lineEdit_ptc_get_4 = QLineEdit(self.groupBox_3)
        self.lineEdit_ptc_get_4.setObjectName(u"lineEdit_ptc_get_4")
        self.lineEdit_ptc_get_4.setGeometry(QRect(250, 70, 41, 22))
        self.lineEdit_ptc_pwm_1 = QLineEdit(self.groupBox_3)
        self.lineEdit_ptc_pwm_1.setObjectName(u"lineEdit_ptc_pwm_1")
        self.lineEdit_ptc_pwm_1.setGeometry(QRect(100, 100, 41, 22))
        self.label_13 = QLabel(self.groupBox_3)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(50, 100, 50, 16))
        self.lineEdit_ptc_pwm_2 = QLineEdit(self.groupBox_3)
        self.lineEdit_ptc_pwm_2.setObjectName(u"lineEdit_ptc_pwm_2")
        self.lineEdit_ptc_pwm_2.setGeometry(QRect(150, 100, 41, 22))
        self.lineEdit_ptc_pwm_3 = QLineEdit(self.groupBox_3)
        self.lineEdit_ptc_pwm_3.setObjectName(u"lineEdit_ptc_pwm_3")
        self.lineEdit_ptc_pwm_3.setGeometry(QRect(200, 100, 41, 22))
        self.lineEdit_ptc_pwm_4 = QLineEdit(self.groupBox_3)
        self.lineEdit_ptc_pwm_4.setObjectName(u"lineEdit_ptc_pwm_4")
        self.lineEdit_ptc_pwm_4.setGeometry(QRect(250, 100, 41, 22))
        self.tabWidget.addTab(self.tab_spine, "")
        self.tab_air = QWidget()
        self.tab_air.setObjectName(u"tab_air")
        self.groupBox_2 = QGroupBox(self.tab_air)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(10, 10, 561, 351))
        self.lineEdit_room_status_1 = QLineEdit(self.groupBox_2)
        self.lineEdit_room_status_1.setObjectName(u"lineEdit_room_status_1")
        self.lineEdit_room_status_1.setGeometry(QRect(140, 310, 61, 22))
        self.label_27 = QLabel(self.groupBox_2)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(150, 250, 50, 16))
        self.lineEdit_room_status_2 = QLineEdit(self.groupBox_2)
        self.lineEdit_room_status_2.setObjectName(u"lineEdit_room_status_2")
        self.lineEdit_room_status_2.setGeometry(QRect(210, 310, 61, 22))
        self.lineEdit_room_status_3 = QLineEdit(self.groupBox_2)
        self.lineEdit_room_status_3.setObjectName(u"lineEdit_room_status_3")
        self.lineEdit_room_status_3.setGeometry(QRect(280, 310, 61, 22))
        self.lineEdit_room_status_4 = QLineEdit(self.groupBox_2)
        self.lineEdit_room_status_4.setObjectName(u"lineEdit_room_status_4")
        self.lineEdit_room_status_4.setGeometry(QRect(350, 310, 61, 22))
        self.lineEdit_room_status_5 = QLineEdit(self.groupBox_2)
        self.lineEdit_room_status_5.setObjectName(u"lineEdit_room_status_5")
        self.lineEdit_room_status_5.setGeometry(QRect(420, 310, 61, 22))
        self.lineEdit_room_status_6 = QLineEdit(self.groupBox_2)
        self.lineEdit_room_status_6.setObjectName(u"lineEdit_room_status_6")
        self.lineEdit_room_status_6.setGeometry(QRect(490, 310, 61, 22))
        self.label_28 = QLabel(self.groupBox_2)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(220, 250, 50, 16))
        self.label_29 = QLabel(self.groupBox_2)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(290, 250, 50, 16))
        self.label_30 = QLabel(self.groupBox_2)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(360, 250, 50, 16))
        self.label_31 = QLabel(self.groupBox_2)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(430, 250, 50, 16))
        self.label_32 = QLabel(self.groupBox_2)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(500, 250, 50, 16))
        self.label_33 = QLabel(self.groupBox_2)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setGeometry(QRect(40, 310, 81, 16))
        self.lineEdit_room_set_4 = QLineEdit(self.groupBox_2)
        self.lineEdit_room_set_4.setObjectName(u"lineEdit_room_set_4")
        self.lineEdit_room_set_4.setGeometry(QRect(350, 280, 61, 22))
        self.lineEdit_room_set_3 = QLineEdit(self.groupBox_2)
        self.lineEdit_room_set_3.setObjectName(u"lineEdit_room_set_3")
        self.lineEdit_room_set_3.setGeometry(QRect(280, 280, 61, 22))
        self.lineEdit_room_set_5 = QLineEdit(self.groupBox_2)
        self.lineEdit_room_set_5.setObjectName(u"lineEdit_room_set_5")
        self.lineEdit_room_set_5.setGeometry(QRect(420, 280, 61, 22))
        self.lineEdit_room_set_2 = QLineEdit(self.groupBox_2)
        self.lineEdit_room_set_2.setObjectName(u"lineEdit_room_set_2")
        self.lineEdit_room_set_2.setGeometry(QRect(210, 280, 61, 22))
        self.lineEdit_room_set_1 = QLineEdit(self.groupBox_2)
        self.lineEdit_room_set_1.setObjectName(u"lineEdit_room_set_1")
        self.lineEdit_room_set_1.setGeometry(QRect(140, 280, 61, 22))
        self.lineEdit_room_set_6 = QLineEdit(self.groupBox_2)
        self.lineEdit_room_set_6.setObjectName(u"lineEdit_room_set_6")
        self.lineEdit_room_set_6.setGeometry(QRect(490, 280, 61, 22))
        self.label_34 = QLabel(self.groupBox_2)
        self.label_34.setObjectName(u"label_34")
        self.label_34.setGeometry(QRect(40, 280, 81, 16))
        self.lineEdit_solvalve_vol_status = QLineEdit(self.groupBox_2)
        self.lineEdit_solvalve_vol_status.setObjectName(u"lineEdit_solvalve_vol_status")
        self.lineEdit_solvalve_vol_status.setGeometry(QRect(140, 210, 61, 22))
        self.label_35 = QLabel(self.groupBox_2)
        self.label_35.setObjectName(u"label_35")
        self.label_35.setGeometry(QRect(40, 210, 81, 16))
        self.label_37 = QLabel(self.groupBox_2)
        self.label_37.setObjectName(u"label_37")
        self.label_37.setGeometry(QRect(340, 70, 81, 16))
        self.lineEdit_airpump_duty = QLineEdit(self.groupBox_2)
        self.lineEdit_airpump_duty.setObjectName(u"lineEdit_airpump_duty")
        self.lineEdit_airpump_duty.setGeometry(QRect(420, 70, 61, 22))
        self.lineEdit_airpump_state = QLineEdit(self.groupBox_2)
        self.lineEdit_airpump_state.setObjectName(u"lineEdit_airpump_state")
        self.lineEdit_airpump_state.setGeometry(QRect(420, 40, 61, 22))
        self.label_38 = QLabel(self.groupBox_2)
        self.label_38.setObjectName(u"label_38")
        self.label_38.setGeometry(QRect(340, 40, 81, 16))
        self.comboBox_air_strength = QComboBox(self.groupBox_2)
        self.comboBox_air_strength.setObjectName(u"comboBox_air_strength")
        self.comboBox_air_strength.setGeometry(QRect(200, 70, 111, 22))
        self.comboBox_air_mode = QComboBox(self.groupBox_2)
        self.comboBox_air_mode.setObjectName(u"comboBox_air_mode")
        self.comboBox_air_mode.setGeometry(QRect(200, 40, 107, 24))
        self.comboBox_air_mode.setMaximumSize(QSize(16777215, 16777215))
        self.comboBox_air_mode.setSizeAdjustPolicy(QComboBox.SizeAdjustPolicy.AdjustToContents)
        self.comboBox_air_mode.setMinimumContentsLength(10)
        self.label_71 = QLabel(self.groupBox_2)
        self.label_71.setObjectName(u"label_71")
        self.label_71.setGeometry(QRect(150, 70, 50, 20))
        self.label_72 = QLabel(self.groupBox_2)
        self.label_72.setObjectName(u"label_72")
        self.label_72.setGeometry(QRect(150, 40, 50, 20))
        self.label_73 = QLabel(self.groupBox_2)
        self.label_73.setObjectName(u"label_73")
        self.label_73.setGeometry(QRect(340, 100, 81, 16))
        self.lineEdit_airpump_duty_type = QLineEdit(self.groupBox_2)
        self.lineEdit_airpump_duty_type.setObjectName(u"lineEdit_airpump_duty_type")
        self.lineEdit_airpump_duty_type.setGeometry(QRect(420, 100, 131, 22))
        self.lineEdit_airmassage_state = QLineEdit(self.groupBox_2)
        self.lineEdit_airmassage_state.setObjectName(u"lineEdit_airmassage_state")
        self.lineEdit_airmassage_state.setGeometry(QRect(140, 160, 61, 22))
        self.label_74 = QLabel(self.groupBox_2)
        self.label_74.setObjectName(u"label_74")
        self.label_74.setGeometry(QRect(30, 160, 91, 16))
        self.btn_air_play = QPushButton(self.groupBox_2)
        self.btn_air_play.setObjectName(u"btn_air_play")
        self.btn_air_play.setGeometry(QRect(20, 40, 75, 24))
        self.btn_air_pause = QPushButton(self.groupBox_2)
        self.btn_air_pause.setObjectName(u"btn_air_pause")
        self.btn_air_pause.setGeometry(QRect(20, 70, 75, 24))
        self.lineEdit_air_pressure = QLineEdit(self.groupBox_2)
        self.lineEdit_air_pressure.setObjectName(u"lineEdit_air_pressure")
        self.lineEdit_air_pressure.setGeometry(QRect(310, 160, 61, 22))
        self.label_75 = QLabel(self.groupBox_2)
        self.label_75.setObjectName(u"label_75")
        self.label_75.setGeometry(QRect(220, 160, 81, 16))
        self.lineEdit_air_fit = QLineEdit(self.groupBox_2)
        self.lineEdit_air_fit.setObjectName(u"lineEdit_air_fit")
        self.lineEdit_air_fit.setGeometry(QRect(310, 190, 111, 22))
        self.label_76 = QLabel(self.groupBox_2)
        self.label_76.setObjectName(u"label_76")
        self.label_76.setGeometry(QRect(220, 190, 81, 16))
        self.label_77 = QLabel(self.groupBox_2)
        self.label_77.setObjectName(u"label_77")
        self.label_77.setGeometry(QRect(380, 160, 81, 16))
        self.tabWidget.addTab(self.tab_air, "")
        self.tab_heater = QWidget()
        self.tab_heater.setObjectName(u"tab_heater")
        self.groupBox_4 = QGroupBox(self.tab_heater)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(10, 10, 561, 381))
        self.lineEdit_heater_arm_temp_target = QLineEdit(self.groupBox_4)
        self.lineEdit_heater_arm_temp_target.setObjectName(u"lineEdit_heater_arm_temp_target")
        self.lineEdit_heater_arm_temp_target.setGeometry(QRect(190, 40, 81, 22))
        self.label_17 = QLabel(self.groupBox_4)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(30, 40, 71, 20))
        self.label_18 = QLabel(self.groupBox_4)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(110, 20, 71, 20))
        self.label_19 = QLabel(self.groupBox_4)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(250, 20, 81, 20))
        self.label_20 = QLabel(self.groupBox_4)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(30, 70, 71, 20))
        self.lineEdit_heater_arm_l_temp_current = QLineEdit(self.groupBox_4)
        self.lineEdit_heater_arm_l_temp_current.setObjectName(u"lineEdit_heater_arm_l_temp_current")
        self.lineEdit_heater_arm_l_temp_current.setGeometry(QRect(110, 70, 81, 22))
        self.lineEdit_heater_arm_r_temp_current = QLineEdit(self.groupBox_4)
        self.lineEdit_heater_arm_r_temp_current.setObjectName(u"lineEdit_heater_arm_r_temp_current")
        self.lineEdit_heater_arm_r_temp_current.setGeometry(QRect(250, 70, 81, 22))
        self.label_21 = QLabel(self.groupBox_4)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(30, 100, 71, 20))
        self.lineEdit_heater_arm_l_current = QLineEdit(self.groupBox_4)
        self.lineEdit_heater_arm_l_current.setObjectName(u"lineEdit_heater_arm_l_current")
        self.lineEdit_heater_arm_l_current.setGeometry(QRect(110, 100, 81, 22))
        self.lineEdit_heater_arm_r_current = QLineEdit(self.groupBox_4)
        self.lineEdit_heater_arm_r_current.setObjectName(u"lineEdit_heater_arm_r_current")
        self.lineEdit_heater_arm_r_current.setGeometry(QRect(250, 100, 81, 22))
        self.lineEdit_heater_arm_l_set = QLineEdit(self.groupBox_4)
        self.lineEdit_heater_arm_l_set.setObjectName(u"lineEdit_heater_arm_l_set")
        self.lineEdit_heater_arm_l_set.setGeometry(QRect(110, 130, 81, 22))
        self.label_22 = QLabel(self.groupBox_4)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(30, 130, 71, 20))
        self.lineEdit_heater_arm_r_set = QLineEdit(self.groupBox_4)
        self.lineEdit_heater_arm_r_set.setObjectName(u"lineEdit_heater_arm_r_set")
        self.lineEdit_heater_arm_r_set.setGeometry(QRect(250, 130, 81, 22))
        self.btn_heater_set_arm = QPushButton(self.groupBox_4)
        self.btn_heater_set_arm.setObjectName(u"btn_heater_set_arm")
        self.btn_heater_set_arm.setGeometry(QRect(340, 40, 75, 24))
        self.label_23 = QLabel(self.groupBox_4)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(200, 100, 20, 20))
        self.label_24 = QLabel(self.groupBox_4)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(340, 100, 20, 20))
        self.label_25 = QLabel(self.groupBox_4)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(200, 70, 41, 20))
        self.label_26 = QLabel(self.groupBox_4)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(340, 70, 41, 20))
        self.btn_heater_set_cush = QPushButton(self.groupBox_4)
        self.btn_heater_set_cush.setObjectName(u"btn_heater_set_cush")
        self.btn_heater_set_cush.setGeometry(QRect(198, 220, 75, 24))
        self.lineEdit_heater_cush_current = QLineEdit(self.groupBox_4)
        self.lineEdit_heater_cush_current.setObjectName(u"lineEdit_heater_cush_current")
        self.lineEdit_heater_cush_current.setGeometry(QRect(108, 280, 81, 22))
        self.label_39 = QLabel(self.groupBox_4)
        self.label_39.setObjectName(u"label_39")
        self.label_39.setGeometry(QRect(128, 200, 51, 20))
        self.lineEdit_heater_cush_set = QLineEdit(self.groupBox_4)
        self.lineEdit_heater_cush_set.setObjectName(u"lineEdit_heater_cush_set")
        self.lineEdit_heater_cush_set.setGeometry(QRect(108, 310, 81, 22))
        self.lineEdit_heater_cush_temp_current = QLineEdit(self.groupBox_4)
        self.lineEdit_heater_cush_temp_current.setObjectName(u"lineEdit_heater_cush_temp_current")
        self.lineEdit_heater_cush_temp_current.setGeometry(QRect(108, 250, 81, 22))
        self.label_40 = QLabel(self.groupBox_4)
        self.label_40.setObjectName(u"label_40")
        self.label_40.setGeometry(QRect(198, 280, 20, 20))
        self.label_41 = QLabel(self.groupBox_4)
        self.label_41.setObjectName(u"label_41")
        self.label_41.setGeometry(QRect(198, 250, 41, 20))
        self.lineEdit_heater_cush_temp_target = QLineEdit(self.groupBox_4)
        self.lineEdit_heater_cush_temp_target.setObjectName(u"lineEdit_heater_cush_temp_target")
        self.lineEdit_heater_cush_temp_target.setGeometry(QRect(110, 220, 81, 22))
        self.label_42 = QLabel(self.groupBox_4)
        self.label_42.setObjectName(u"label_42")
        self.label_42.setGeometry(QRect(30, 220, 71, 20))
        self.label_43 = QLabel(self.groupBox_4)
        self.label_43.setObjectName(u"label_43")
        self.label_43.setGeometry(QRect(30, 250, 71, 20))
        self.label_44 = QLabel(self.groupBox_4)
        self.label_44.setObjectName(u"label_44")
        self.label_44.setGeometry(QRect(30, 280, 71, 20))
        self.label_45 = QLabel(self.groupBox_4)
        self.label_45.setObjectName(u"label_45")
        self.label_45.setGeometry(QRect(30, 310, 71, 20))
        self.btn_heater_set_leg = QPushButton(self.groupBox_4)
        self.btn_heater_set_leg.setObjectName(u"btn_heater_set_leg")
        self.btn_heater_set_leg.setGeometry(QRect(390, 220, 75, 24))
        self.lineEdit_heater_leg_temp_target = QLineEdit(self.groupBox_4)
        self.lineEdit_heater_leg_temp_target.setObjectName(u"lineEdit_heater_leg_temp_target")
        self.lineEdit_heater_leg_temp_target.setGeometry(QRect(302, 220, 81, 22))
        self.label_46 = QLabel(self.groupBox_4)
        self.label_46.setObjectName(u"label_46")
        self.label_46.setGeometry(QRect(320, 200, 51, 20))
        self.lineEdit_heater_leg_temp_current = QLineEdit(self.groupBox_4)
        self.lineEdit_heater_leg_temp_current.setObjectName(u"lineEdit_heater_leg_temp_current")
        self.lineEdit_heater_leg_temp_current.setGeometry(QRect(300, 250, 81, 22))
        self.lineEdit_heater_leg_set = QLineEdit(self.groupBox_4)
        self.lineEdit_heater_leg_set.setObjectName(u"lineEdit_heater_leg_set")
        self.lineEdit_heater_leg_set.setGeometry(QRect(300, 310, 81, 22))
        self.label_47 = QLabel(self.groupBox_4)
        self.label_47.setObjectName(u"label_47")
        self.label_47.setGeometry(QRect(390, 250, 41, 20))
        self.lineEdit_heater_leg_current = QLineEdit(self.groupBox_4)
        self.lineEdit_heater_leg_current.setObjectName(u"lineEdit_heater_leg_current")
        self.lineEdit_heater_leg_current.setGeometry(QRect(300, 280, 81, 22))
        self.label_48 = QLabel(self.groupBox_4)
        self.label_48.setObjectName(u"label_48")
        self.label_48.setGeometry(QRect(390, 280, 20, 20))
        self.tabWidget.addTab(self.tab_heater, "")
        self.tab_reclining = QWidget()
        self.tab_reclining.setObjectName(u"tab_reclining")
        self.groupBox_5 = QGroupBox(self.tab_reclining)
        self.groupBox_5.setObjectName(u"groupBox_5")
        self.groupBox_5.setGeometry(QRect(10, 20, 571, 91))
        self.btn_reclining_up = QPushButton(self.groupBox_5)
        self.btn_reclining_up.setObjectName(u"btn_reclining_up")
        self.btn_reclining_up.setGeometry(QRect(10, 20, 71, 24))
        self.label_14 = QLabel(self.groupBox_5)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(260, 20, 50, 20))
        self.lineEdit_reclining_get_angle = QLineEdit(self.groupBox_5)
        self.lineEdit_reclining_get_angle.setObjectName(u"lineEdit_reclining_get_angle")
        self.lineEdit_reclining_get_angle.setGeometry(QRect(310, 20, 81, 22))
        self.btn_reclining_down = QPushButton(self.groupBox_5)
        self.btn_reclining_down.setObjectName(u"btn_reclining_down")
        self.btn_reclining_down.setGeometry(QRect(90, 20, 71, 24))
        self.btn_reclining_stop = QPushButton(self.groupBox_5)
        self.btn_reclining_stop.setObjectName(u"btn_reclining_stop")
        self.btn_reclining_stop.setGeometry(QRect(170, 20, 71, 24))
        self.lineEdit_reclining_get_state = QLineEdit(self.groupBox_5)
        self.lineEdit_reclining_get_state.setObjectName(u"lineEdit_reclining_get_state")
        self.lineEdit_reclining_get_state.setGeometry(QRect(450, 20, 51, 22))
        self.label_15 = QLabel(self.groupBox_5)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(400, 20, 50, 20))
        self.groupBox_6 = QGroupBox(self.tab_reclining)
        self.groupBox_6.setObjectName(u"groupBox_6")
        self.groupBox_6.setGeometry(QRect(10, 140, 571, 101))
        self.btn_legrest_up = QPushButton(self.groupBox_6)
        self.btn_legrest_up.setObjectName(u"btn_legrest_up")
        self.btn_legrest_up.setGeometry(QRect(10, 20, 75, 24))
        self.btn_legrest_down = QPushButton(self.groupBox_6)
        self.btn_legrest_down.setObjectName(u"btn_legrest_down")
        self.btn_legrest_down.setGeometry(QRect(90, 20, 75, 24))
        self.btn_legrest_stop = QPushButton(self.groupBox_6)
        self.btn_legrest_stop.setObjectName(u"btn_legrest_stop")
        self.btn_legrest_stop.setGeometry(QRect(170, 20, 75, 24))
        self.lineEdit_legrest_state = QLineEdit(self.groupBox_6)
        self.lineEdit_legrest_state.setObjectName(u"lineEdit_legrest_state")
        self.lineEdit_legrest_state.setGeometry(QRect(310, 20, 81, 22))
        self.label_16 = QLabel(self.groupBox_6)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(260, 20, 50, 16))
        self.tabWidget.addTab(self.tab_reclining, "")
        self.tab_audio = QWidget()
        self.tab_audio.setObjectName(u"tab_audio")
        self.lineEdit_audio_name = QLineEdit(self.tab_audio)
        self.lineEdit_audio_name.setObjectName(u"lineEdit_audio_name")
        self.lineEdit_audio_name.setGeometry(QRect(70, 20, 171, 22))
        self.label_36 = QLabel(self.tab_audio)
        self.label_36.setObjectName(u"label_36")
        self.label_36.setGeometry(QRect(10, 20, 48, 16))
        self.lineEdit_audio_reset = QLineEdit(self.tab_audio)
        self.lineEdit_audio_reset.setObjectName(u"lineEdit_audio_reset")
        self.lineEdit_audio_reset.setGeometry(QRect(140, 60, 60, 20))
        self.label_49 = QLabel(self.tab_audio)
        self.label_49.setObjectName(u"label_49")
        self.label_49.setGeometry(QRect(10, 60, 130, 16))
        self.label_50 = QLabel(self.tab_audio)
        self.label_50.setObjectName(u"label_50")
        self.label_50.setGeometry(QRect(10, 85, 130, 16))
        self.lineEdit_audio_sdcard = QLineEdit(self.tab_audio)
        self.lineEdit_audio_sdcard.setObjectName(u"lineEdit_audio_sdcard")
        self.lineEdit_audio_sdcard.setGeometry(QRect(140, 85, 60, 20))
        self.lineEdit_audio_bt_pair = QLineEdit(self.tab_audio)
        self.lineEdit_audio_bt_pair.setObjectName(u"lineEdit_audio_bt_pair")
        self.lineEdit_audio_bt_pair.setGeometry(QRect(140, 110, 60, 20))
        self.label_51 = QLabel(self.tab_audio)
        self.label_51.setObjectName(u"label_51")
        self.label_51.setGeometry(QRect(10, 110, 130, 16))
        self.label_52 = QLabel(self.tab_audio)
        self.label_52.setObjectName(u"label_52")
        self.label_52.setGeometry(QRect(10, 135, 130, 16))
        self.lineEdit_audio_bt_auto_pair = QLineEdit(self.tab_audio)
        self.lineEdit_audio_bt_auto_pair.setObjectName(u"lineEdit_audio_bt_auto_pair")
        self.lineEdit_audio_bt_auto_pair.setGeometry(QRect(140, 135, 60, 20))
        self.lineEdit_audio_sound_select = QLineEdit(self.tab_audio)
        self.lineEdit_audio_sound_select.setObjectName(u"lineEdit_audio_sound_select")
        self.lineEdit_audio_sound_select.setGeometry(QRect(140, 160, 60, 20))
        self.label_53 = QLabel(self.tab_audio)
        self.label_53.setObjectName(u"label_53")
        self.label_53.setGeometry(QRect(10, 160, 130, 16))
        self.label_54 = QLabel(self.tab_audio)
        self.label_54.setObjectName(u"label_54")
        self.label_54.setGeometry(QRect(440, 60, 181, 16))
        self.lineEdit_audio_voice_recg_state = QLineEdit(self.tab_audio)
        self.lineEdit_audio_voice_recg_state.setObjectName(u"lineEdit_audio_voice_recg_state")
        self.lineEdit_audio_voice_recg_state.setGeometry(QRect(620, 60, 60, 20))
        self.lineEdit_audio_mp3_pwr_state = QLineEdit(self.tab_audio)
        self.lineEdit_audio_mp3_pwr_state.setObjectName(u"lineEdit_audio_mp3_pwr_state")
        self.lineEdit_audio_mp3_pwr_state.setGeometry(QRect(140, 220, 60, 20))
        self.label_55 = QLabel(self.tab_audio)
        self.label_55.setObjectName(u"label_55")
        self.label_55.setGeometry(QRect(10, 220, 130, 16))
        self.lineEdit_audio_sd_loop_setting = QLineEdit(self.tab_audio)
        self.lineEdit_audio_sd_loop_setting.setObjectName(u"lineEdit_audio_sd_loop_setting")
        self.lineEdit_audio_sd_loop_setting.setGeometry(QRect(140, 250, 60, 20))
        self.label_56 = QLabel(self.tab_audio)
        self.label_56.setObjectName(u"label_56")
        self.label_56.setGeometry(QRect(10, 250, 130, 16))
        self.label_57 = QLabel(self.tab_audio)
        self.label_57.setObjectName(u"label_57")
        self.label_57.setGeometry(QRect(10, 280, 130, 16))
        self.lineEdit_audio_sd_play_mode = QLineEdit(self.tab_audio)
        self.lineEdit_audio_sd_play_mode.setObjectName(u"lineEdit_audio_sd_play_mode")
        self.lineEdit_audio_sd_play_mode.setGeometry(QRect(140, 280, 60, 20))
        self.lineEdit_audio_bt_connect_state = QLineEdit(self.tab_audio)
        self.lineEdit_audio_bt_connect_state.setObjectName(u"lineEdit_audio_bt_connect_state")
        self.lineEdit_audio_bt_connect_state.setGeometry(QRect(140, 310, 60, 20))
        self.label_58 = QLabel(self.tab_audio)
        self.label_58.setObjectName(u"label_58")
        self.label_58.setGeometry(QRect(10, 310, 130, 16))
        self.lineEdit_audio_music_volume = QLineEdit(self.tab_audio)
        self.lineEdit_audio_music_volume.setObjectName(u"lineEdit_audio_music_volume")
        self.lineEdit_audio_music_volume.setGeometry(QRect(140, 340, 60, 20))
        self.label_59 = QLabel(self.tab_audio)
        self.label_59.setObjectName(u"label_59")
        self.label_59.setGeometry(QRect(10, 340, 130, 16))
        self.label_60 = QLabel(self.tab_audio)
        self.label_60.setObjectName(u"label_60")
        self.label_60.setGeometry(QRect(10, 370, 130, 16))
        self.lineEdit_audio_voice_volume = QLineEdit(self.tab_audio)
        self.lineEdit_audio_voice_volume.setObjectName(u"lineEdit_audio_voice_volume")
        self.lineEdit_audio_voice_volume.setGeometry(QRect(140, 370, 60, 20))
        self.label_61 = QLabel(self.tab_audio)
        self.label_61.setObjectName(u"label_61")
        self.label_61.setGeometry(QRect(210, 110, 130, 16))
        self.label_62 = QLabel(self.tab_audio)
        self.label_62.setObjectName(u"label_62")
        self.label_62.setGeometry(QRect(210, 160, 130, 16))
        self.lineEdit_audio_select_track_tm = QLineEdit(self.tab_audio)
        self.lineEdit_audio_select_track_tm.setObjectName(u"lineEdit_audio_select_track_tm")
        self.lineEdit_audio_select_track_tm.setGeometry(QRect(345, 220, 181, 20))
        self.label_63 = QLabel(self.tab_audio)
        self.label_63.setObjectName(u"label_63")
        self.label_63.setGeometry(QRect(210, 340, 130, 16))
        self.label_64 = QLabel(self.tab_audio)
        self.label_64.setObjectName(u"label_64")
        self.label_64.setGeometry(QRect(210, 60, 130, 16))
        self.label_65 = QLabel(self.tab_audio)
        self.label_65.setObjectName(u"label_65")
        self.label_65.setGeometry(QRect(210, 250, 130, 16))
        self.lineEdit_audio_music_level = QLineEdit(self.tab_audio)
        self.lineEdit_audio_music_level.setObjectName(u"lineEdit_audio_music_level")
        self.lineEdit_audio_music_level.setGeometry(QRect(345, 340, 80, 20))
        self.lineEdit_audio_trackinfo_word = QLineEdit(self.tab_audio)
        self.lineEdit_audio_trackinfo_word.setObjectName(u"lineEdit_audio_trackinfo_word")
        self.lineEdit_audio_trackinfo_word.setGeometry(QRect(345, 250, 80, 20))
        self.lineEdit_audio_trackinfo_title = QLineEdit(self.tab_audio)
        self.lineEdit_audio_trackinfo_title.setObjectName(u"lineEdit_audio_trackinfo_title")
        self.lineEdit_audio_trackinfo_title.setGeometry(QRect(345, 310, 80, 20))
        self.lineEdit_audio_trackinfo_singer = QLineEdit(self.tab_audio)
        self.lineEdit_audio_trackinfo_singer.setObjectName(u"lineEdit_audio_trackinfo_singer")
        self.lineEdit_audio_trackinfo_singer.setGeometry(QRect(345, 280, 80, 20))
        self.lineEdit_audio_play_state = QLineEdit(self.tab_audio)
        self.lineEdit_audio_play_state.setObjectName(u"lineEdit_audio_play_state")
        self.lineEdit_audio_play_state.setGeometry(QRect(345, 85, 80, 20))
        self.lineEdit_audio_voice_recg_value = QLineEdit(self.tab_audio)
        self.lineEdit_audio_voice_recg_value.setObjectName(u"lineEdit_audio_voice_recg_value")
        self.lineEdit_audio_voice_recg_value.setGeometry(QRect(345, 370, 80, 20))
        self.label_66 = QLabel(self.tab_audio)
        self.label_66.setObjectName(u"label_66")
        self.label_66.setGeometry(QRect(210, 310, 130, 16))
        self.label_67 = QLabel(self.tab_audio)
        self.label_67.setObjectName(u"label_67")
        self.label_67.setGeometry(QRect(210, 85, 130, 16))
        self.lineEdit_audio_mp3_version = QLineEdit(self.tab_audio)
        self.lineEdit_audio_mp3_version.setObjectName(u"lineEdit_audio_mp3_version")
        self.lineEdit_audio_mp3_version.setGeometry(QRect(345, 135, 80, 20))
        self.label_68 = QLabel(self.tab_audio)
        self.label_68.setObjectName(u"label_68")
        self.label_68.setGeometry(QRect(210, 280, 130, 16))
        self.lineEdit_audio_voice_version = QLineEdit(self.tab_audio)
        self.lineEdit_audio_voice_version.setObjectName(u"lineEdit_audio_voice_version")
        self.lineEdit_audio_voice_version.setGeometry(QRect(345, 110, 80, 20))
        self.label_69 = QLabel(self.tab_audio)
        self.label_69.setObjectName(u"label_69")
        self.label_69.setGeometry(QRect(210, 370, 130, 16))
        self.lineEdit_audio_music_track_sel = QLineEdit(self.tab_audio)
        self.lineEdit_audio_music_track_sel.setObjectName(u"lineEdit_audio_music_track_sel")
        self.lineEdit_audio_music_track_sel.setGeometry(QRect(345, 190, 80, 20))
        self.label_70 = QLabel(self.tab_audio)
        self.label_70.setObjectName(u"label_70")
        self.label_70.setGeometry(QRect(210, 135, 130, 16))
        self.label_78 = QLabel(self.tab_audio)
        self.label_78.setObjectName(u"label_78")
        self.label_78.setGeometry(QRect(210, 190, 130, 16))
        self.label_79 = QLabel(self.tab_audio)
        self.label_79.setObjectName(u"label_79")
        self.label_79.setGeometry(QRect(210, 220, 130, 16))
        self.lineEdit_audio_music_count = QLineEdit(self.tab_audio)
        self.lineEdit_audio_music_count.setObjectName(u"lineEdit_audio_music_count")
        self.lineEdit_audio_music_count.setGeometry(QRect(345, 60, 80, 20))
        self.lineEdit_audio_sd_version = QLineEdit(self.tab_audio)
        self.lineEdit_audio_sd_version.setObjectName(u"lineEdit_audio_sd_version")
        self.lineEdit_audio_sd_version.setGeometry(QRect(345, 160, 80, 20))
        self.groupBox_8 = QGroupBox(self.tab_audio)
        self.groupBox_8.setObjectName(u"groupBox_8")
        self.groupBox_8.setGeometry(QRect(0, 400, 541, 181))
        self.label_85 = QLabel(self.groupBox_8)
        self.label_85.setObjectName(u"label_85")
        self.label_85.setGeometry(QRect(280, 60, 121, 20))
        self.comboBox_audio_bt_pair = QComboBox(self.groupBox_8)
        self.comboBox_audio_bt_pair.setObjectName(u"comboBox_audio_bt_pair")
        self.comboBox_audio_bt_pair.setGeometry(QRect(150, 90, 107, 24))
        self.comboBox_audio_bt_pair.setMaximumSize(QSize(16777215, 16777215))
        self.comboBox_audio_bt_pair.setSizeAdjustPolicy(QComboBox.SizeAdjustPolicy.AdjustToContents)
        self.comboBox_audio_bt_pair.setMinimumContentsLength(10)
        self.label_87 = QLabel(self.groupBox_8)
        self.label_87.setObjectName(u"label_87")
        self.label_87.setGeometry(QRect(280, 90, 130, 16))
        self.btn_audio_ctrl_stop = QPushButton(self.groupBox_8)
        self.btn_audio_ctrl_stop.setObjectName(u"btn_audio_ctrl_stop")
        self.btn_audio_ctrl_stop.setGeometry(QRect(440, 130, 80, 24))
        self.btn_audio_ctrl_play = QPushButton(self.groupBox_8)
        self.btn_audio_ctrl_play.setObjectName(u"btn_audio_ctrl_play")
        self.btn_audio_ctrl_play.setGeometry(QRect(280, 130, 80, 24))
        self.lineEdit_audio_ctrl_voice_volume = QLineEdit(self.groupBox_8)
        self.lineEdit_audio_ctrl_voice_volume.setObjectName(u"lineEdit_audio_ctrl_voice_volume")
        self.lineEdit_audio_ctrl_voice_volume.setGeometry(QRect(410, 60, 81, 22))
        self.label_83 = QLabel(self.groupBox_8)
        self.label_83.setObjectName(u"label_83")
        self.label_83.setGeometry(QRect(20, 120, 130, 16))
        self.btn_audio_ctrl_pause = QPushButton(self.groupBox_8)
        self.btn_audio_ctrl_pause.setObjectName(u"btn_audio_ctrl_pause")
        self.btn_audio_ctrl_pause.setGeometry(QRect(360, 130, 80, 24))
        self.label_82 = QLabel(self.groupBox_8)
        self.label_82.setObjectName(u"label_82")
        self.label_82.setGeometry(QRect(20, 90, 130, 16))
        self.label_80 = QLabel(self.groupBox_8)
        self.label_80.setObjectName(u"label_80")
        self.label_80.setGeometry(QRect(20, 30, 130, 16))
        self.comboBox_audio_select_sound = QComboBox(self.groupBox_8)
        self.comboBox_audio_select_sound.setObjectName(u"comboBox_audio_select_sound")
        self.comboBox_audio_select_sound.setGeometry(QRect(150, 30, 107, 24))
        self.comboBox_audio_select_sound.setMaximumSize(QSize(16777215, 16777215))
        self.comboBox_audio_select_sound.setSizeAdjustPolicy(QComboBox.SizeAdjustPolicy.AdjustToContents)
        self.comboBox_audio_select_sound.setMinimumContentsLength(10)
        self.comboBox_audio_song_select = QComboBox(self.groupBox_8)
        self.comboBox_audio_song_select.setObjectName(u"comboBox_audio_song_select")
        self.comboBox_audio_song_select.setGeometry(QRect(410, 90, 107, 24))
        self.comboBox_audio_song_select.setMaximumSize(QSize(16777215, 16777215))
        self.comboBox_audio_song_select.setSizeAdjustPolicy(QComboBox.SizeAdjustPolicy.AdjustToContents)
        self.comboBox_audio_song_select.setMinimumContentsLength(10)
        self.label_86 = QLabel(self.groupBox_8)
        self.label_86.setObjectName(u"label_86")
        self.label_86.setGeometry(QRect(20, 150, 130, 16))
        self.comboBox_audio_select_track = QComboBox(self.groupBox_8)
        self.comboBox_audio_select_track.setObjectName(u"comboBox_audio_select_track")
        self.comboBox_audio_select_track.setGeometry(QRect(150, 150, 107, 24))
        self.comboBox_audio_select_track.setMaximumSize(QSize(16777215, 16777215))
        self.comboBox_audio_select_track.setSizeAdjustPolicy(QComboBox.SizeAdjustPolicy.AdjustToContents)
        self.comboBox_audio_select_track.setMinimumContentsLength(10)
        self.comboBox_audio_reset = QComboBox(self.groupBox_8)
        self.comboBox_audio_reset.setObjectName(u"comboBox_audio_reset")
        self.comboBox_audio_reset.setGeometry(QRect(150, 120, 107, 24))
        self.comboBox_audio_reset.setMaximumSize(QSize(16777215, 16777215))
        self.comboBox_audio_reset.setSizeAdjustPolicy(QComboBox.SizeAdjustPolicy.AdjustToContents)
        self.comboBox_audio_reset.setMinimumContentsLength(10)
        self.comboBox_audio_bt_auto_pair = QComboBox(self.groupBox_8)
        self.comboBox_audio_bt_auto_pair.setObjectName(u"comboBox_audio_bt_auto_pair")
        self.comboBox_audio_bt_auto_pair.setGeometry(QRect(150, 60, 107, 24))
        self.comboBox_audio_bt_auto_pair.setMaximumSize(QSize(16777215, 16777215))
        self.comboBox_audio_bt_auto_pair.setSizeAdjustPolicy(QComboBox.SizeAdjustPolicy.AdjustToContents)
        self.comboBox_audio_bt_auto_pair.setMinimumContentsLength(10)
        self.label_84 = QLabel(self.groupBox_8)
        self.label_84.setObjectName(u"label_84")
        self.label_84.setGeometry(QRect(280, 30, 121, 20))
        self.lineEdit_audio_ctrl_music_volume = QLineEdit(self.groupBox_8)
        self.lineEdit_audio_ctrl_music_volume.setObjectName(u"lineEdit_audio_ctrl_music_volume")
        self.lineEdit_audio_ctrl_music_volume.setGeometry(QRect(410, 30, 81, 22))
        self.label_81 = QLabel(self.groupBox_8)
        self.label_81.setObjectName(u"label_81")
        self.label_81.setGeometry(QRect(20, 60, 130, 16))
        self.label_88 = QLabel(self.tab_audio)
        self.label_88.setObjectName(u"label_88")
        self.label_88.setGeometry(QRect(260, 10, 130, 16))
        self.lineEdit_audio_play_state_bt = QLineEdit(self.tab_audio)
        self.lineEdit_audio_play_state_bt.setObjectName(u"lineEdit_audio_play_state_bt")
        self.lineEdit_audio_play_state_bt.setGeometry(QRect(390, 10, 60, 20))
        self.lineEdit_audio_play_state_sd = QLineEdit(self.tab_audio)
        self.lineEdit_audio_play_state_sd.setObjectName(u"lineEdit_audio_play_state_sd")
        self.lineEdit_audio_play_state_sd.setGeometry(QRect(390, 30, 60, 20))
        self.label_89 = QLabel(self.tab_audio)
        self.label_89.setObjectName(u"label_89")
        self.label_89.setGeometry(QRect(260, 30, 130, 16))
        self.lineEdit_audio_eq = QLineEdit(self.tab_audio)
        self.lineEdit_audio_eq.setObjectName(u"lineEdit_audio_eq")
        self.lineEdit_audio_eq.setGeometry(QRect(140, 190, 60, 20))
        self.label_90 = QLabel(self.tab_audio)
        self.label_90.setObjectName(u"label_90")
        self.label_90.setGeometry(QRect(10, 190, 91, 16))
        self.tabWidget.addTab(self.tab_audio, "")
        self.groupBox_8.raise_()
        self.lineEdit_audio_name.raise_()
        self.label_36.raise_()
        self.lineEdit_audio_reset.raise_()
        self.label_49.raise_()
        self.label_50.raise_()
        self.lineEdit_audio_sdcard.raise_()
        self.lineEdit_audio_bt_pair.raise_()
        self.label_51.raise_()
        self.label_52.raise_()
        self.lineEdit_audio_bt_auto_pair.raise_()
        self.lineEdit_audio_sound_select.raise_()
        self.label_53.raise_()
        self.label_54.raise_()
        self.lineEdit_audio_voice_recg_state.raise_()
        self.lineEdit_audio_mp3_pwr_state.raise_()
        self.label_55.raise_()
        self.lineEdit_audio_sd_loop_setting.raise_()
        self.label_56.raise_()
        self.label_57.raise_()
        self.lineEdit_audio_sd_play_mode.raise_()
        self.lineEdit_audio_bt_connect_state.raise_()
        self.label_58.raise_()
        self.lineEdit_audio_music_volume.raise_()
        self.label_59.raise_()
        self.label_60.raise_()
        self.lineEdit_audio_voice_volume.raise_()
        self.label_61.raise_()
        self.label_62.raise_()
        self.lineEdit_audio_select_track_tm.raise_()
        self.label_63.raise_()
        self.label_64.raise_()
        self.label_65.raise_()
        self.lineEdit_audio_music_level.raise_()
        self.lineEdit_audio_trackinfo_word.raise_()
        self.lineEdit_audio_trackinfo_title.raise_()
        self.lineEdit_audio_trackinfo_singer.raise_()
        self.lineEdit_audio_play_state.raise_()
        self.lineEdit_audio_voice_recg_value.raise_()
        self.label_66.raise_()
        self.label_67.raise_()
        self.lineEdit_audio_mp3_version.raise_()
        self.label_68.raise_()
        self.lineEdit_audio_voice_version.raise_()
        self.label_69.raise_()
        self.lineEdit_audio_music_track_sel.raise_()
        self.label_70.raise_()
        self.label_78.raise_()
        self.label_79.raise_()
        self.lineEdit_audio_music_count.raise_()
        self.lineEdit_audio_sd_version.raise_()
        self.label_88.raise_()
        self.lineEdit_audio_play_state_bt.raise_()
        self.lineEdit_audio_play_state_sd.raise_()
        self.label_89.raise_()
        self.lineEdit_audio_eq.raise_()
        self.label_90.raise_()
        self.tab_rmc = QWidget()
        self.tab_rmc.setObjectName(u"tab_rmc")
        self.groupBox_7 = QGroupBox(self.tab_rmc)
        self.groupBox_7.setObjectName(u"groupBox_7")
        self.groupBox_7.setGeometry(QRect(0, 0, 571, 91))
        self.btn_rmc_power_on = QPushButton(self.groupBox_7)
        self.btn_rmc_power_on.setObjectName(u"btn_rmc_power_on")
        self.btn_rmc_power_on.setGeometry(QRect(10, 20, 71, 24))
        self.btn_rmc_power_off = QPushButton(self.groupBox_7)
        self.btn_rmc_power_off.setObjectName(u"btn_rmc_power_off")
        self.btn_rmc_power_off.setGeometry(QRect(90, 20, 71, 24))
        self.tabWidget.addTab(self.tab_rmc, "")
        self.tab_hb = QWidget()
        self.tab_hb.setObjectName(u"tab_hb")
        self.groupBox_15 = QGroupBox(self.tab_hb)
        self.groupBox_15.setObjectName(u"groupBox_15")
        self.groupBox_15.setGeometry(QRect(10, 10, 561, 251))
        self.btn_ext_dev_play = QPushButton(self.groupBox_15)
        self.btn_ext_dev_play.setObjectName(u"btn_ext_dev_play")
        self.btn_ext_dev_play.setGeometry(QRect(10, 30, 75, 24))
        self.comboBox_ext_dev_mode = QComboBox(self.groupBox_15)
        self.comboBox_ext_dev_mode.setObjectName(u"comboBox_ext_dev_mode")
        self.comboBox_ext_dev_mode.setGeometry(QRect(240, 30, 107, 24))
        self.comboBox_ext_dev_mode.setMaximumSize(QSize(16777215, 16777215))
        self.comboBox_ext_dev_mode.setSizeAdjustPolicy(QComboBox.SizeAdjustPolicy.AdjustToContents)
        self.comboBox_ext_dev_mode.setMinimumContentsLength(10)
        self.btn_ext_dev_stop = QPushButton(self.groupBox_15)
        self.btn_ext_dev_stop.setObjectName(u"btn_ext_dev_stop")
        self.btn_ext_dev_stop.setGeometry(QRect(10, 90, 75, 24))
        self.btn_ext_dev_pause = QPushButton(self.groupBox_15)
        self.btn_ext_dev_pause.setObjectName(u"btn_ext_dev_pause")
        self.btn_ext_dev_pause.setGeometry(QRect(10, 60, 75, 24))
        self.label_107 = QLabel(self.groupBox_15)
        self.label_107.setObjectName(u"label_107")
        self.label_107.setGeometry(QRect(190, 30, 50, 20))
        self.comboBox_ext_dev_strength = QComboBox(self.groupBox_15)
        self.comboBox_ext_dev_strength.setObjectName(u"comboBox_ext_dev_strength")
        self.comboBox_ext_dev_strength.setGeometry(QRect(240, 60, 111, 22))
        self.label_108 = QLabel(self.groupBox_15)
        self.label_108.setObjectName(u"label_108")
        self.label_108.setGeometry(QRect(190, 60, 50, 20))
        self.lineEdit_ext_dev_status = QPushButton(self.groupBox_15)
        self.lineEdit_ext_dev_status.setObjectName(u"lineEdit_ext_dev_status")
        self.lineEdit_ext_dev_status.setGeometry(QRect(90, 30, 75, 24))
        self.LineEdit_ext_dev_temp_set = QLineEdit(self.groupBox_15)
        self.LineEdit_ext_dev_temp_set.setObjectName(u"LineEdit_ext_dev_temp_set")
        self.LineEdit_ext_dev_temp_set.setGeometry(QRect(260, 90, 41, 22))
        self.btn_ext_dev_temp_set = QPushButton(self.groupBox_15)
        self.btn_ext_dev_temp_set.setObjectName(u"btn_ext_dev_temp_set")
        self.btn_ext_dev_temp_set.setGeometry(QRect(170, 90, 75, 24))
        self.lineEdit_ext_dev_cur_temp = QLineEdit(self.groupBox_15)
        self.lineEdit_ext_dev_cur_temp.setObjectName(u"lineEdit_ext_dev_cur_temp")
        self.lineEdit_ext_dev_cur_temp.setGeometry(QRect(100, 120, 81, 22))
        self.label_109 = QLabel(self.groupBox_15)
        self.label_109.setObjectName(u"label_109")
        self.label_109.setGeometry(QRect(20, 120, 71, 20))
        self.tabWidget.addTab(self.tab_hb, "")

        self.horizontalLayout_4.addWidget(self.frame_2)

        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)

        self.verticalLayout_4.addWidget(self.scrollArea)


        self.horizontalLayout_2.addWidget(self.frame)


        self.verticalLayout.addLayout(self.horizontalLayout_2)


        self.horizontalLayout_3.addLayout(self.verticalLayout)


        self.retranslateUi(CAN)

        self.tabWidget.setCurrentIndex(4)


        QMetaObject.connectSlotsByName(CAN)
    # setupUi

    def retranslateUi(self, CAN):
        CAN.setWindowTitle(QCoreApplication.translate("CAN", u"Form", None))
        self.combo_open_mode.setItemText(0, QCoreApplication.translate("CAN", u"NORMAL", None))
        self.combo_open_mode.setItemText(1, QCoreApplication.translate("CAN", u"MONITOR", None))
        self.combo_open_mode.setItemText(2, QCoreApplication.translate("CAN", u"LOOPBACK", None))

        self.label.setText(QCoreApplication.translate("CAN", u"BAUD", None))
        self.btn_open.setText(QCoreApplication.translate("CAN", u"Open", None))
        self.btn_close.setText(QCoreApplication.translate("CAN", u"Close", None))
        self.label_rx_cnt.setText(QCoreApplication.translate("CAN", u"RX CNT :", None))
        self.label_rx_size.setText(QCoreApplication.translate("CAN", u"RX SIZE :", None))
        self.label_1111.setText(QCoreApplication.translate("CAN", u"BLDC", None))
        self.btn_send_1.setText(QCoreApplication.translate("CAN", u"Send", None))
        self.lineEdit_send_1.setText(QCoreApplication.translate("CAN", u"0", None))
        self.lineEdit_send_2.setText(QCoreApplication.translate("CAN", u"0", None))
        self.btn_send_2.setText(QCoreApplication.translate("CAN", u"Send", None))
        self.lineEdit_send_3.setText(QCoreApplication.translate("CAN", u"0", None))
        self.btn_send_3.setText(QCoreApplication.translate("CAN", u"Send", None))
        self.lineEdit_send_4.setText(QCoreApplication.translate("CAN", u"0", None))
        self.btn_send_4.setText(QCoreApplication.translate("CAN", u"Send", None))
        self.label_1.setText(QCoreApplication.translate("CAN", u"0", None))
        self.label_2.setText(QCoreApplication.translate("CAN", u"0", None))
        self.label_3.setText(QCoreApplication.translate("CAN", u"0", None))
        self.label_4.setText(QCoreApplication.translate("CAN", u"0", None))
        self.groupBox.setTitle(QCoreApplication.translate("CAN", u"Spine Massage", None))
        self.checkBox_scan.setText(QCoreApplication.translate("CAN", u"SCAN", None))
        self.btn_spine_play.setText(QCoreApplication.translate("CAN", u"Play", None))
        self.btn_spine_stop.setText(QCoreApplication.translate("CAN", u"Stop", None))
        self.btn_spine_pause.setText(QCoreApplication.translate("CAN", u"Pause", None))
        self.label_5.setText(QCoreApplication.translate("CAN", u"Mode", None))
        self.label_6.setText(QCoreApplication.translate("CAN", u"\uc138\uae30", None))
        self.pushButton.setText(QCoreApplication.translate("CAN", u"_", None))
        self.label_7.setText(QCoreApplication.translate("CAN", u"Speed", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("CAN", u"PTC", None))
        self.btn_ptc_set.setText(QCoreApplication.translate("CAN", u"Set", None))
        self.label_8.setText(QCoreApplication.translate("CAN", u"1", None))
        self.label_9.setText(QCoreApplication.translate("CAN", u"2", None))
        self.label_10.setText(QCoreApplication.translate("CAN", u"3", None))
        self.label_11.setText(QCoreApplication.translate("CAN", u"4", None))
        self.label_12.setText(QCoreApplication.translate("CAN", u"\ud604\uc7ac\uac12", None))
        self.label_13.setText(QCoreApplication.translate("CAN", u"PWM", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_spine), QCoreApplication.translate("CAN", u"Spine", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("CAN", u"Air Massage", None))
        self.lineEdit_room_status_1.setText("")
        self.label_27.setText(QCoreApplication.translate("CAN", u"Room1", None))
        self.lineEdit_room_status_2.setText("")
        self.lineEdit_room_status_3.setText("")
        self.lineEdit_room_status_4.setText("")
        self.lineEdit_room_status_5.setText("")
        self.lineEdit_room_status_6.setText("")
        self.label_28.setText(QCoreApplication.translate("CAN", u"Room2", None))
        self.label_29.setText(QCoreApplication.translate("CAN", u"Room3", None))
        self.label_30.setText(QCoreApplication.translate("CAN", u"Room4", None))
        self.label_31.setText(QCoreApplication.translate("CAN", u"Room5", None))
        self.label_32.setText(QCoreApplication.translate("CAN", u"Room6", None))
        self.label_33.setText(QCoreApplication.translate("CAN", u"\ubc38\ube0c \uc0c1\ud0dc", None))
        self.lineEdit_room_set_4.setText("")
        self.lineEdit_room_set_3.setText("")
        self.lineEdit_room_set_5.setText("")
        self.lineEdit_room_set_2.setText("")
        self.lineEdit_room_set_1.setText("")
        self.lineEdit_room_set_6.setText("")
        self.label_34.setText(QCoreApplication.translate("CAN", u"\ubc38\ube0c \uc81c\uc5b4", None))
        self.lineEdit_solvalve_vol_status.setText("")
        self.label_35.setText(QCoreApplication.translate("CAN", u"\ubc38\ube0c \uc804\uc555", None))
        self.label_37.setText(QCoreApplication.translate("CAN", u"\ud38c\ud504 \ub4c0\ud2f0", None))
        self.lineEdit_airpump_duty.setText("")
        self.lineEdit_airpump_state.setText("")
        self.label_38.setText(QCoreApplication.translate("CAN", u"\ud38c\ud504 \uc0c1\ud0dc", None))
        self.label_71.setText(QCoreApplication.translate("CAN", u"\uc138\uae30", None))
        self.label_72.setText(QCoreApplication.translate("CAN", u"Mode", None))
        self.label_73.setText(QCoreApplication.translate("CAN", u"\ud38c\ud504 \ud0c0\uc785", None))
        self.lineEdit_airpump_duty_type.setText("")
        self.lineEdit_airmassage_state.setText("")
        self.label_74.setText(QCoreApplication.translate("CAN", u"\ub9c8\uc0ac\uc9c0 \uc0c1\ud0dc", None))
        self.btn_air_play.setText(QCoreApplication.translate("CAN", u"Play", None))
        self.btn_air_pause.setText(QCoreApplication.translate("CAN", u"Pause", None))
        self.lineEdit_air_pressure.setText("")
        self.label_75.setText(QCoreApplication.translate("CAN", u"\uc555\ub825 \uc0c1\ud0dc", None))
        self.lineEdit_air_fit.setText("")
        self.label_76.setText(QCoreApplication.translate("CAN", u"AirFit", None))
        self.label_77.setText(QCoreApplication.translate("CAN", u"mBar", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_air), QCoreApplication.translate("CAN", u"Air", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("CAN", u"Heater", None))
        self.label_17.setText(QCoreApplication.translate("CAN", u"\ubaa9\ud45c\uc628\ub3c4", None))
        self.label_18.setText(QCoreApplication.translate("CAN", u"Arm Left", None))
        self.label_19.setText(QCoreApplication.translate("CAN", u"Arm Right", None))
        self.label_20.setText(QCoreApplication.translate("CAN", u"\ud604\uc7ac\uc628\ub3c4", None))
        self.label_21.setText(QCoreApplication.translate("CAN", u"\ud604\uc7ac\uc804\ub958", None))
        self.label_22.setText(QCoreApplication.translate("CAN", u"\ucd9c\ub825\uc81c\uc5b4", None))
        self.btn_heater_set_arm.setText(QCoreApplication.translate("CAN", u"Set", None))
        self.label_23.setText(QCoreApplication.translate("CAN", u"mA", None))
        self.label_24.setText(QCoreApplication.translate("CAN", u"mA", None))
        self.label_25.setText(QCoreApplication.translate("CAN", u"0.1\ub3c4", None))
        self.label_26.setText(QCoreApplication.translate("CAN", u"0.1\ub3c4", None))
        self.btn_heater_set_cush.setText(QCoreApplication.translate("CAN", u"Set", None))
        self.label_39.setText(QCoreApplication.translate("CAN", u"Cush", None))
        self.label_40.setText(QCoreApplication.translate("CAN", u"mA", None))
        self.label_41.setText(QCoreApplication.translate("CAN", u"0.1\ub3c4", None))
        self.label_42.setText(QCoreApplication.translate("CAN", u"\ubaa9\ud45c\uc628\ub3c4", None))
        self.label_43.setText(QCoreApplication.translate("CAN", u"\ud604\uc7ac\uc628\ub3c4", None))
        self.label_44.setText(QCoreApplication.translate("CAN", u"\ud604\uc7ac\uc804\ub958", None))
        self.label_45.setText(QCoreApplication.translate("CAN", u"\ucd9c\ub825\uc81c\uc5b4", None))
        self.btn_heater_set_leg.setText(QCoreApplication.translate("CAN", u"Set", None))
        self.label_46.setText(QCoreApplication.translate("CAN", u"Leg", None))
        self.label_47.setText(QCoreApplication.translate("CAN", u"0.1\ub3c4", None))
        self.label_48.setText(QCoreApplication.translate("CAN", u"mA", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_heater), QCoreApplication.translate("CAN", u"Heater", None))
        self.groupBox_5.setTitle(QCoreApplication.translate("CAN", u"Reclining", None))
        self.btn_reclining_up.setText(QCoreApplication.translate("CAN", u"Up", None))
        self.label_14.setText(QCoreApplication.translate("CAN", u"Angle", None))
        self.btn_reclining_down.setText(QCoreApplication.translate("CAN", u"Down", None))
        self.btn_reclining_stop.setText(QCoreApplication.translate("CAN", u"Stop", None))
        self.label_15.setText(QCoreApplication.translate("CAN", u"State", None))
        self.groupBox_6.setTitle(QCoreApplication.translate("CAN", u"Legrest", None))
        self.btn_legrest_up.setText(QCoreApplication.translate("CAN", u"Up", None))
        self.btn_legrest_down.setText(QCoreApplication.translate("CAN", u"Down", None))
        self.btn_legrest_stop.setText(QCoreApplication.translate("CAN", u"Stop", None))
        self.label_16.setText(QCoreApplication.translate("CAN", u"State", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_reclining), QCoreApplication.translate("CAN", u"Reclining/Legrest", None))
        self.label_36.setText(QCoreApplication.translate("CAN", u"NAME", None))
        self.label_49.setText(QCoreApplication.translate("CAN", u"RESET", None))
        self.label_50.setText(QCoreApplication.translate("CAN", u"SD CARD DETECT", None))
        self.label_51.setText(QCoreApplication.translate("CAN", u"BT Pair", None))
        self.label_52.setText(QCoreApplication.translate("CAN", u"BT Auto Pair", None))
        self.label_53.setText(QCoreApplication.translate("CAN", u"Sound Select", None))
        self.label_54.setText(QCoreApplication.translate("CAN", u"Voice Rocg Power State", None))
        self.label_55.setText(QCoreApplication.translate("CAN", u"MP3 Power State", None))
        self.label_56.setText(QCoreApplication.translate("CAN", u"SD Loop Setting", None))
        self.label_57.setText(QCoreApplication.translate("CAN", u"SD Play Mode", None))
        self.label_58.setText(QCoreApplication.translate("CAN", u"BT Connect State", None))
        self.label_59.setText(QCoreApplication.translate("CAN", u"Music Volume", None))
        self.label_60.setText(QCoreApplication.translate("CAN", u"Voice Volume", None))
        self.label_61.setText(QCoreApplication.translate("CAN", u"Voice Version", None))
        self.label_62.setText(QCoreApplication.translate("CAN", u"SD Version", None))
        self.label_63.setText(QCoreApplication.translate("CAN", u"Music Level", None))
        self.label_64.setText(QCoreApplication.translate("CAN", u"Music Count", None))
        self.label_65.setText(QCoreApplication.translate("CAN", u"TrackInfo Word", None))
        self.label_66.setText(QCoreApplication.translate("CAN", u"TrackInfo Title", None))
        self.label_67.setText(QCoreApplication.translate("CAN", u"Track Play State", None))
        self.label_68.setText(QCoreApplication.translate("CAN", u"TrackInfo Singer", None))
        self.label_69.setText(QCoreApplication.translate("CAN", u"Voice Recg Vaule", None))
        self.label_70.setText(QCoreApplication.translate("CAN", u"MP3 Version", None))
        self.label_78.setText(QCoreApplication.translate("CAN", u"Music Track Sel", None))
        self.label_79.setText(QCoreApplication.translate("CAN", u"Track Time", None))
        self.groupBox_8.setTitle(QCoreApplication.translate("CAN", u"RMC \uc81c\uc5b4", None))
        self.label_85.setText(QCoreApplication.translate("CAN", u"Voice Volume", None))
        self.label_87.setText(QCoreApplication.translate("CAN", u"Song Select", None))
        self.btn_audio_ctrl_stop.setText(QCoreApplication.translate("CAN", u"STOP", None))
        self.btn_audio_ctrl_play.setText(QCoreApplication.translate("CAN", u"PLAY", None))
        self.label_83.setText(QCoreApplication.translate("CAN", u"Reset", None))
        self.btn_audio_ctrl_pause.setText(QCoreApplication.translate("CAN", u"PAUSE", None))
        self.label_82.setText(QCoreApplication.translate("CAN", u"BT Pair", None))
        self.label_80.setText(QCoreApplication.translate("CAN", u"Select Sound", None))
        self.label_86.setText(QCoreApplication.translate("CAN", u"Music Control", None))
        self.label_84.setText(QCoreApplication.translate("CAN", u"Music Volume", None))
        self.label_81.setText(QCoreApplication.translate("CAN", u"BT Auto Pair", None))
        self.label_88.setText(QCoreApplication.translate("CAN", u"BT Play State", None))
        self.label_89.setText(QCoreApplication.translate("CAN", u"SD Play State", None))
        self.label_90.setText(QCoreApplication.translate("CAN", u"EQ", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_audio), QCoreApplication.translate("CAN", u"Audio", None))
        self.groupBox_7.setTitle(QCoreApplication.translate("CAN", u"Power", None))
        self.btn_rmc_power_on.setText(QCoreApplication.translate("CAN", u"On", None))
        self.btn_rmc_power_off.setText(QCoreApplication.translate("CAN", u"Off", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_rmc), QCoreApplication.translate("CAN", u"RMC", None))
        self.groupBox_15.setTitle(QCoreApplication.translate("CAN", u"Massage", None))
        self.btn_ext_dev_play.setText(QCoreApplication.translate("CAN", u"Play", None))
        self.btn_ext_dev_stop.setText(QCoreApplication.translate("CAN", u"Stop", None))
        self.btn_ext_dev_pause.setText(QCoreApplication.translate("CAN", u"Pause", None))
        self.label_107.setText(QCoreApplication.translate("CAN", u"Mode", None))
        self.label_108.setText(QCoreApplication.translate("CAN", u"\uc138\uae30", None))
        self.lineEdit_ext_dev_status.setText(QCoreApplication.translate("CAN", u"_", None))
        self.btn_ext_dev_temp_set.setText(QCoreApplication.translate("CAN", u"Set", None))
        self.label_109.setText(QCoreApplication.translate("CAN", u"\ud604\uc7ac\uc628\ub3c4", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_hb), QCoreApplication.translate("CAN", u"ExtDev", None))
    # retranslateUi

